CREATE TABLE IF NOT EXISTS blog_posts (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    slug VARCHAR(255) NOT NULL UNIQUE,
    slug_en VARCHAR(255) UNIQUE,
    title VARCHAR(500) NOT NULL,
    title_en VARCHAR(500),
    meta_description VARCHAR(300),
    meta_description_en VARCHAR(300),
    excerpt TEXT,
    excerpt_en TEXT,
    content_markdown LONGTEXT NOT NULL,
    content_markdown_en LONGTEXT,
    content_html LONGTEXT NOT NULL,
    content_html_en LONGTEXT,
    featured_image VARCHAR(500),
    author_name VARCHAR(255) DEFAULT 'Tim Jagad Shalawat',
    category VARCHAR(100),
    tags JSON,
    source_url VARCHAR(500),
    source_name VARCHAR(255),
    status ENUM('draft','published','archived') DEFAULT 'draft',
    published_at TIMESTAMP NULL,
    reading_time_minutes TINYINT UNSIGNED DEFAULT 1,
    view_count BIGINT UNSIGNED DEFAULT 0,
    is_featured BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_status_published (status, published_at DESC),
    INDEX idx_category (category),
    INDEX idx_featured (is_featured, published_at DESC),
    FULLTEXT INDEX ft_search (title, content_markdown)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS blog_comments (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    post_id BIGINT UNSIGNED NOT NULL,
    parent_id BIGINT UNSIGNED NULL,
    author_name VARCHAR(255) NOT NULL,
    author_email VARCHAR(255),
    author_avatar_url VARCHAR(500),
    oauth_provider ENUM('google','github') NULL,
    oauth_id VARCHAR(255) NULL,
    content TEXT NOT NULL,
    status ENUM('pending','approved','rejected','spam') DEFAULT 'pending',
    rejection_reason VARCHAR(255),
    ip_address VARCHAR(45),
    user_agent VARCHAR(500),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (post_id) REFERENCES blog_posts(id) ON DELETE CASCADE,
    FOREIGN KEY (parent_id) REFERENCES blog_comments(id) ON DELETE SET NULL,
    INDEX idx_post_status (post_id, status, created_at),
    INDEX idx_oauth (oauth_provider, oauth_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS blog_blocked_words (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    word VARCHAR(255) NOT NULL,
    category ENUM('gambling','sara','pornography','spam','other') NOT NULL,
    is_regex BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UNIQUE INDEX idx_word (word)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS blog_admin_users (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(100) NOT NULL UNIQUE,
    email VARCHAR(255) UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    display_name VARCHAR(255),
    role ENUM('admin', 'contributor') DEFAULT 'admin',
    is_active BOOLEAN DEFAULT TRUE,
    reset_token VARCHAR(255) UNIQUE,
    reset_token_expires_at TIMESTAMP NULL,
    last_login_at TIMESTAMP NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
