CREATE TABLE IF NOT EXISTS blog_posts (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    slug VARCHAR(255) NOT NULL UNIQUE,
    slug_en VARCHAR(255) UNIQUE,
    title VARCHAR(500) NOT NULL,
    title_en VARCHAR(500),
    meta_description VARCHAR(300),
    meta_description_en VARCHAR(300),
    excerpt TEXT,
    excerpt_en TEXT,
    content_markdown LONGTEXT NOT NULL,
    content_markdown_en LONGTEXT,
    content_html LONGTEXT NOT NULL,
    content_html_en LONGTEXT,
    featured_image VARCHAR(500),
    author_name VARCHAR(255) DEFAULT 'Tim Tagih Otomatis',
    category VARCHAR(100),
    tags JSON,
    sources JSON,
    source_url VARCHAR(500),
    source_name VARCHAR(255),
    status ENUM('draft','published','archived') DEFAULT 'draft',
    published_at TIMESTAMP NULL,
    reading_time_minutes TINYINT UNSIGNED DEFAULT 1,
    view_count BIGINT UNSIGNED DEFAULT 0,
    is_featured BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_status_published (status, published_at DESC),
    INDEX idx_category (category),
    INDEX idx_featured (is_featured, published_at DESC),
    FULLTEXT INDEX ft_search (title, content_markdown)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
