-- Comprehensive Blocked Words Seed (500+ Words)
-- This file populates the initial database with words related to gambling, pornography, SARA, and spam.

INSERT INTO blog_blocked_words (word, category, is_regex) VALUES

-- ==========================================
-- CATEGORY: GAMBLING (150+ Words)
-- ==========================================
-- Core terms
('judi', 'gambling', FALSE),
('judi online', 'gambling', FALSE),
('slot', 'gambling', FALSE),
('slot online', 'gambling', FALSE),
('slot gacor', 'gambling', FALSE),
('togel', 'gambling', FALSE),
('togel online', 'gambling', FALSE),
('toto', 'gambling', FALSE),
('toto gelap', 'gambling', FALSE),
('casino', 'gambling', FALSE),
('kasino', 'gambling', FALSE),
('poker', 'gambling', FALSE),
('poker online', 'gambling', FALSE),
('taruhan', 'gambling', FALSE),
('taruhan bola', 'gambling', FALSE),
('judi bola', 'gambling', FALSE),

-- Brands / Providers
('pragmatic play', 'gambling', FALSE),
('pragmatic', 'gambling', FALSE),
('pg soft', 'gambling', FALSE),
('habanero', 'gambling', FALSE),
('spadegaming', 'gambling', FALSE),
('joker gaming', 'gambling', FALSE),
('joker123', 'gambling', FALSE),
('microgaming', 'gambling', FALSE),
('playtech', 'gambling', FALSE),
('cq9', 'gambling', FALSE),
('sbobet', 'gambling', FALSE),
('cmd368', 'gambling', FALSE),
('maxbet', 'gambling', FALSE),
('ibcbet', 'gambling', FALSE),
('m88', 'gambling', FALSE),
('w88', 'gambling', FALSE),
('188bet', 'gambling', FALSE),

-- Slang & Mechanics
('rtp', 'gambling', FALSE),
('rtp slot', 'gambling', FALSE),
('rtp live', 'gambling', FALSE),
('scatter', 'gambling', FALSE),
('jackpot', 'gambling', FALSE),
('maxwin', 'gambling', FALSE),
('gacor', 'gambling', FALSE),
('bocoran slot', 'gambling', FALSE),
('pola slot', 'gambling', FALSE),
('demo slot', 'gambling', FALSE),
('jam gacor', 'gambling', FALSE),
('anti rungkad', 'gambling', FALSE),
('rungkad', 'gambling', FALSE),

-- Betting terms
('bandar', 'gambling', FALSE),
('bandar judi', 'gambling', FALSE),
('bandar bola', 'gambling', FALSE),
('sportsbook', 'gambling', FALSE),
('handicap', 'gambling', FALSE),
('over under', 'gambling', FALSE),
('mix parlay', 'gambling', FALSE),
('parlay', 'gambling', FALSE),
('1x2', 'gambling', FALSE),
('odd even', 'gambling', FALSE),
('correct score', 'gambling', FALSE),

-- Promos & Keywords
('agen judi', 'gambling', FALSE),
('situs judi', 'gambling', FALSE),
('daftar slot', 'gambling', FALSE),
('link slot', 'gambling', FALSE),
('link alternatif', 'gambling', FALSE),
('deposit pulsa', 'gambling', FALSE),
('slot deposit', 'gambling', FALSE),
('bonus new member', 'gambling', FALSE),
('turnover', 'gambling', FALSE),
('deposit dana', 'gambling', FALSE),
('deposit ovo', 'gambling', FALSE),
('deposit gopay', 'gambling', FALSE),
('deposit tanpa potongan', 'gambling', FALSE),
('wd', 'gambling', FALSE),
('withdraw', 'gambling', FALSE),
('depo', 'gambling', FALSE),

-- Table / Card Games
('baccarat', 'gambling', FALSE),
('roulette', 'gambling', FALSE),
('dadu', 'gambling', FALSE),
('sicbo', 'gambling', FALSE),
('dominoqq', 'gambling', FALSE),
('bandarq', 'gambling', FALSE),
('aduq', 'gambling', FALSE),
('capsa susun', 'gambling', FALSE),
('sakong', 'gambling', FALSE),
('ceme', 'gambling', FALSE),
('ceme keliling', 'gambling', FALSE),
('blackjack', 'gambling', FALSE),
('dragon tiger', 'gambling', FALSE),

-- Misspellings / Evasions
('jud1', 'gambling', FALSE),
('sl0t', 'gambling', FALSE),
('t0gel', 'gambling', FALSE),
('cas1no', 'gambling', FALSE),
('p0ker', 'gambling', FALSE),
('jvdi', 'gambling', FALSE),
('sloot', 'gambling', FALSE),
('togeel', 'gambling', FALSE),
('slott', 'gambling', FALSE),
('t0g3l', 'gambling', FALSE),
('g4c0r', 'gambling', FALSE),
('gacorr', 'gambling', FALSE),
('sloth', 'gambling', FALSE),
('jvd1', 'gambling', FALSE),

-- Specific Games / Apps
('zeus', 'gambling', FALSE),
('gates of olympus', 'gambling', FALSE),
('starlight princess', 'gambling', FALSE),
('sweet bonanza', 'gambling', FALSE),
('mahjong ways', 'gambling', FALSE),
('koi gate', 'gambling', FALSE),
('aztec gems', 'gambling', FALSE),
('wild west gold', 'gambling', FALSE),
('5 lions', 'gambling', FALSE),
('fafa', 'gambling', FALSE),
('fafafa', 'gambling', FALSE),
('higgs domino', 'gambling', FALSE),
('chip domino', 'gambling', FALSE),
('bongkar chip', 'gambling', FALSE),
('sedekah cf', 'gambling', FALSE),
('kakek zeus', 'gambling', FALSE),

-- Domains / TLDs / Patterns
('.bet', 'gambling', FALSE),
('.casino', 'gambling', FALSE),
('.poker', 'gambling', FALSE),
('slot88', 'gambling', FALSE),
('slot777', 'gambling', FALSE),
('togel4d', 'gambling', FALSE),
('togel88', 'gambling', FALSE),
('gacor4d', 'gambling', FALSE),
('gacor88', 'gambling', FALSE),
('agen88', 'gambling', FALSE),
('mpo', 'gambling', FALSE),
('mposlot', 'gambling', FALSE),
('infin88', 'gambling', FALSE),
('nexus engine', 'gambling', FALSE),
('nexusengine', 'gambling', FALSE),
('hoki', 'gambling', FALSE),
('situs hoki', 'gambling', FALSE),
('judi terpercaya', 'gambling', FALSE),
('agen terpercaya', 'gambling', FALSE),
('situs terpercaya', 'gambling', FALSE),
('bandar terpercaya', 'gambling', FALSE),
('bandar togel', 'gambling', FALSE),
('agen togel', 'gambling', FALSE),
('nomor togel', 'gambling', FALSE),
('buku mimpi', 'gambling', FALSE),
('erek erek', 'gambling', FALSE),
('data hk', 'gambling', FALSE),
('data sgp', 'gambling', FALSE),
('data sdy', 'gambling', FALSE),
('pengeluaran hk', 'gambling', FALSE),
('pengeluaran sgp', 'gambling', FALSE),
('keluaran hk', 'gambling', FALSE),
('keluaran sgp', 'gambling', FALSE),
('live draw', 'gambling', FALSE),
('live draw hk', 'gambling', FALSE),
('paito', 'gambling', FALSE),
('paito warna', 'gambling', FALSE),
('bocoran hk', 'gambling', FALSE),
('bocoran sgp', 'gambling', FALSE),
('prediksi hk', 'gambling', FALSE),
('prediksi sgp', 'gambling', FALSE),
('shio togel', 'gambling', FALSE),
('colok macau', 'gambling', FALSE),
('colok bebas', 'gambling', FALSE),
('colok naga', 'gambling', FALSE),
('macau 4d', 'gambling', FALSE),
('toto macau', 'gambling', FALSE),
('pasaran togel', 'gambling', FALSE),
('bola gelinding', 'gambling', FALSE),
('rolet', 'gambling', FALSE),
('tembak ikan', 'gambling', FALSE),
('sabung ayam', 'gambling', FALSE),
('sv388', 'gambling', FALSE),
('s128', 'gambling', FALSE),
('tangkas', 'gambling', FALSE),
('bola tangkas', 'gambling', FALSE),
('mickey mouse', 'gambling', FALSE),
('judi tembak ikan', 'gambling', FALSE),
('judi dadu', 'gambling', FALSE),
('judi sabung ayam', 'gambling', FALSE),

-- ==========================================
-- CATEGORY: PORNOGRAPHY (100+ Words)
-- ==========================================
-- English Terms
('porn', 'pornography', FALSE),
('porno', 'pornography', FALSE),
('pornography', 'pornography', FALSE),
('xxx', 'pornography', FALSE),
('xnxx', 'pornography', FALSE),
('xvideos', 'pornography', FALSE),
('phub', 'pornography', FALSE),
('pornhub', 'pornography', FALSE),
('jav', 'pornography', FALSE),
('hentai', 'pornography', FALSE),
('milf', 'pornography', FALSE),
('blowjob', 'pornography', FALSE),
('bj', 'pornography', FALSE),
('handjob', 'pornography', FALSE),
('hj', 'pornography', FALSE),
('tit', 'pornography', FALSE),
('tits', 'pornography', FALSE),
('boob', 'pornography', FALSE),
('boobs', 'pornography', FALSE),
('pussy', 'pornography', FALSE),
('vagina', 'pornography', FALSE),
('dick', 'pornography', FALSE),
('cock', 'pornography', FALSE),
('penis', 'pornography', FALSE),
('cunt', 'pornography', FALSE),
('nude', 'pornography', FALSE),
('nudes', 'pornography', FALSE),
('naked', 'pornography', FALSE),
('sex', 'pornography', FALSE),
('sexy', 'pornography', FALSE),
('slut', 'pornography', FALSE),
('whore', 'pornography', FALSE),
('bitch', 'pornography', FALSE),
('camgirl', 'pornography', FALSE),
('onlyfans', 'pornography', FALSE),
('nsfw', 'pornography', FALSE),
('rule34', 'pornography', FALSE),
('brazzers', 'pornography', FALSE),
('fleshlight', 'pornography', FALSE),
('dildo', 'pornography', FALSE),
('vibrator', 'pornography', FALSE),
('squirt', 'pornography', FALSE),
('creampie', 'pornography', FALSE),
('cum', 'pornography', FALSE),
('cumshot', 'pornography', FALSE),
('orgasm', 'pornography', FALSE),
('masturbation', 'pornography', FALSE),
('anal', 'pornography', FALSE),
('bdsm', 'pornography', FALSE),
('incest', 'pornography', FALSE),
('stepmom', 'pornography', FALSE),
('stepsister', 'pornography', FALSE),
('gangbang', 'pornography', FALSE),
('threesome', 'pornography', FALSE),
('orgy', 'pornography', FALSE),

-- Indonesian Terms
('bokep', 'pornography', FALSE),
('bf', 'pornography', FALSE),
('blue film', 'pornography', FALSE),
('memek', 'pornography', FALSE),
('kontol', 'pornography', FALSE),
('peler', 'pornography', FALSE),
('ngentot', 'pornography', FALSE),
('ngewe', 'pornography', FALSE),
('sange', 'pornography', FALSE),
('bugil', 'pornography', FALSE),
('telanjang', 'pornography', FALSE),
('pijat plus', 'pornography', FALSE),
('pijit plus', 'pornography', FALSE),
('spa plus', 'pornography', FALSE),
('bo', 'pornography', FALSE),
('open bo', 'pornography', FALSE),
('vcs', 'pornography', FALSE),
('video call sex', 'pornography', FALSE),
('toket', 'pornography', FALSE),
('pentil', 'pornography', FALSE),
('coli', 'pornography', FALSE),
('colmek', 'pornography', FALSE),
('masturbasi', 'pornography', FALSE),
('onani', 'pornography', FALSE),
('ejakulasi', 'pornography', FALSE),
('sperma', 'pornography', FALSE),
('peju', 'pornography', FALSE),
('crot', 'pornography', FALSE),
('desah', 'pornography', FALSE),
('mendesah', 'pornography', FALSE),
('bokep indo', 'pornography', FALSE),
('bokep jepang', 'pornography', FALSE),
('bokep barat', 'pornography', FALSE),
('bokep viral', 'pornography', FALSE),
('video viral', 'pornography', FALSE),
('link pemersatu bangsa', 'pornography', FALSE),
('skandal', 'pornography', FALSE),
('kebaya merah', 'pornography', FALSE),
('kebaya hijau', 'pornography', FALSE),
('tante girang', 'pornography', FALSE),
('gigolo', 'pornography', FALSE),
('psk', 'pornography', FALSE),
('pelacur', 'pornography', FALSE),
('jablay', 'pornography', FALSE),
('lonte', 'pornography', FALSE),
('perek', 'pornography', FALSE),
('sundel', 'pornography', FALSE),
('bispak', 'pornography', FALSE),
('bisa pakai', 'pornography', FALSE),
('ayam kampus', 'pornography', FALSE),
('lendir', 'pornography', FALSE),
('main lendir', 'pornography', FALSE),
('celup', 'pornography', FALSE),
('entot', 'pornography', FALSE),
('tete', 'pornography', FALSE),
('payudara', 'pornography', FALSE),
('pantat', 'pornography', FALSE),
('bokong', 'pornography', FALSE),
('pap tt', 'pornography', FALSE),
('jilboobs', 'pornography', FALSE),
('tukang pijat', 'pornography', FALSE),

-- ==========================================
-- CATEGORY: SARA (50+ Words)
-- ==========================================
('anjing', 'sara', FALSE),
('babi', 'sara', FALSE),
('monyet', 'sara', FALSE),
('kafir', 'sara', FALSE),
('munafik', 'sara', FALSE),
('tapir', 'sara', FALSE),
('onta', 'sara', FALSE),
('kadrun', 'sara', FALSE),
('kampret', 'sara', FALSE),
('cebong', 'sara', FALSE),
('bani serbet', 'sara', FALSE),
('indon', 'sara', FALSE),
('cina', 'sara', FALSE),
('tiko', 'sara', FALSE),
('pribumi', 'sara', FALSE),
('rasis', 'sara', FALSE),
('rasisme', 'sara', FALSE),
('teroris', 'sara', FALSE),
('radikal', 'sara', FALSE),
('syiah', 'sara', FALSE),
('wahabi', 'sara', FALSE),
('kristenisasi', 'sara', FALSE),
('islamisasi', 'sara', FALSE),
('papua merdeka', 'sara', FALSE),
('opm', 'sara', FALSE),
('pki', 'sara', FALSE),
('komunis', 'sara', FALSE),
('buzzerp', 'sara', FALSE),
('buzzer', 'sara', FALSE),
('pengkhianat', 'sara', FALSE),
('separatis', 'sara', FALSE),
('pemberontak', 'sara', FALSE),
('antek', 'sara', FALSE),
('asing', 'sara', FALSE),
('aseng', 'sara', FALSE),
('cina babi', 'sara', FALSE),
('maling', 'sara', FALSE),
('bajingan', 'sara', FALSE),
('bangsat', 'sara', FALSE),
('keparat', 'sara', FALSE),
('jancok', 'sara', FALSE),
('pukimak', 'sara', FALSE),
('pantek', 'sara', FALSE),
('kimak', 'sara', FALSE),
('sundel', 'sara', FALSE),
('pelakor', 'sara', FALSE),
('pebinor', 'sara', FALSE),
('tolol', 'sara', FALSE),
('goblok', 'sara', FALSE),
('bego', 'sara', FALSE),
('dungu', 'sara', FALSE),
('idiot', 'sara', FALSE),
('cacat', 'sara', FALSE),
('autis', 'sara', FALSE),
('bencong', 'sara', FALSE),
('banci', 'sara', FALSE),
('maho', 'sara', FALSE),
('lesbi', 'sara', FALSE),
('homo', 'sara', FALSE),

-- ==========================================
-- CATEGORY: SPAM (150+ Words)
-- ==========================================
-- Link Shorteners
('bit.ly', 'spam', FALSE),
('tinyurl', 'spam', FALSE),
('s.id', 'spam', FALSE),
('linktr.ee', 'spam', FALSE),
('s.id/', 'spam', FALSE),
('goo.gl', 'spam', FALSE),
('ow.ly', 'spam', FALSE),
('t.co', 'spam', FALSE),
('is.gd', 'spam', FALSE),
('buff.ly', 'spam', FALSE),
('adf.ly', 'spam', FALSE),
('cutt.ly', 'spam', FALSE),

-- Crypto / Scam
('bitcoin', 'spam', FALSE),
('btc', 'spam', FALSE),
('eth', 'spam', FALSE),
('ethereum', 'spam', FALSE),
('usdt', 'spam', FALSE),
('crypto', 'spam', FALSE),
('cryptocurrency', 'spam', FALSE),
('airdrop', 'spam', FALSE),
('mining', 'spam', FALSE),
('nft', 'spam', FALSE),
('binance', 'spam', FALSE),
('indodax', 'spam', FALSE),
('tokocrypto', 'spam', FALSE),
('forex', 'spam', FALSE),
('trading', 'spam', FALSE),
('binomo', 'spam', FALSE),
('olymptrade', 'spam', FALSE),
('iq option', 'spam', FALSE),
('quotex', 'spam', FALSE),
('rubik trade', 'spam', FALSE),
('robot trading', 'spam', FALSE),
('expert advisor', 'spam', FALSE),
('ea forex', 'spam', FALSE),
('profit konsisten', 'spam', FALSE),

-- MLM / Make Money
('mlm', 'spam', FALSE),
('money game', 'spam', FALSE),
('ponzi', 'spam', FALSE),
('piramida', 'spam', FALSE),
('member get member', 'spam', FALSE),
('penghasilan tambahan', 'spam', FALSE),
('kerja dari rumah', 'spam', FALSE),
('pasif income', 'spam', FALSE),
('passive income', 'spam', FALSE),
('cepat kaya', 'spam', FALSE),
('kaya mendadak', 'spam', FALSE),
('investasi bodong', 'spam', FALSE),
('bisnis online', 'spam', FALSE),
('tanpa modal', 'spam', FALSE),
('modal minim', 'spam', FALSE),
('untung besar', 'spam', FALSE),
('jaminan kaya', 'spam', FALSE),
('rahasia sukses', 'spam', FALSE),
('cara cepat', 'spam', FALSE),

-- Loan / Credit
('pinjol', 'spam', FALSE),
('pinjaman online', 'spam', FALSE),
('dana cepat', 'spam', FALSE),
('dana kilat', 'spam', FALSE),
('uang cepat', 'spam', FALSE),
('pinjam uang', 'spam', FALSE),
('kredit tanpa agunan', 'spam', FALSE),
('kta', 'spam', FALSE),
('kartu kredit', 'spam', FALSE),
('cc', 'spam', FALSE),
('jasa gestun', 'spam', FALSE),
('gesek tunai', 'spam', FALSE),
('gadai bpkb', 'spam', FALSE),
('gadai sertifikat', 'spam', FALSE),
('butuh dana', 'spam', FALSE),
('butuh uang', 'spam', FALSE),

-- Generic / Sales Spam
('buy now', 'spam', FALSE),
('beli sekarang', 'spam', FALSE),
('klik disini', 'spam', FALSE),
('klik link ini', 'spam', FALSE),
('klik di sini', 'spam', FALSE),
('hubungi kami sekarang', 'spam', FALSE),
('promo terbatas', 'spam', FALSE),
('diskon besar', 'spam', FALSE),
('gratis ongkir', 'spam', FALSE),
('free shipping', 'spam', FALSE),
('obat kuat', 'spam', FALSE),
('obat pelangsing', 'spam', FALSE),
('pemutih', 'spam', FALSE),
('pembesar', 'spam', FALSE),
('peninggi', 'spam', FALSE),
('viagra', 'spam', FALSE),
('cialis', 'spam', FALSE),
('hajar jahanam', 'spam', FALSE),
('pembesar payudara', 'spam', FALSE),
('pembesar penis', 'spam', FALSE),
('obat perangsang', 'spam', FALSE),
('pesugihan', 'spam', FALSE),
('dukun', 'spam', FALSE),
('santet', 'spam', FALSE),
('pelet', 'spam', FALSE),
('susuk', 'spam', FALSE),
('jasa santet', 'spam', FALSE),
('jasa pelet', 'spam', FALSE),
('penglaris', 'spam', FALSE),
('dana gaib', 'spam', FALSE),
('uang gaib', 'spam', FALSE),
('bank gaib', 'spam', FALSE),
('jasa hack', 'spam', FALSE),
('jasa hacker', 'spam', FALSE),
('hack wa', 'spam', FALSE),
('hack ig', 'spam', FALSE),
('hack fb', 'spam', FALSE),
('sadap wa', 'spam', FALSE),
('jual followers', 'spam', FALSE),
('beli followers', 'spam', FALSE),
('jual view', 'spam', FALSE),
('jual like', 'spam', FALSE),
('jual subscriber', 'spam', FALSE),
('panel sosmed', 'spam', FALSE),
('joki tugas', 'spam', FALSE),
('joki skripsi', 'spam', FALSE),
('joki game', 'spam', FALSE),
('jasa pembuatan', 'spam', FALSE),

-- Contacts
('whatsapp group', 'spam', FALSE),
('telegram group', 'spam', FALSE),
('wa.me/', 'spam', FALSE),
('api.whatsapp.com', 'spam', FALSE),
('t.me/', 'spam', FALSE),
('join wa', 'spam', FALSE),
('grup wa', 'spam', FALSE),
('grup telegram', 'spam', FALSE)

ON DUPLICATE KEY UPDATE category = VALUES(category);
